name: Build docker image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker Images and Package
        run: |
          docker pull ubuntu:latest --platform "linux/arm64"
          docker save ubuntu:latest -o ubuntu-latest-arm64.tar"

      - name: Compress the TAR files
        run: tar -czf arm64-images.tar.gz *-arm64.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images-tar
          path: arm64-images.tar.gz
          retention-days: 90  # 将保留天数设置为 1 天 最多可设置90天

      - name: Clean up intermediate files
        run: |
          rm *-arm64.tar