name: Build docker image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t username/my-app:1.0 -f test.Dockerfile .
          docker tag username/my-app:1.0 username/my-app:latest

      - name: Pull Docker Images and Package
        run: |
          docker save my-app:latest -o my-app-latest.tar

      - name: Compress the TAR files
        run: tar -czf my-app-images.tar.gz my-app-latest.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images-tar
          path: my-app-images.tar.gz
          retention-days: 90  # 将保留天数设置为 1 天 最多可设置90天

      - name: Clean up intermediate files
        run: |
          rm my-app-latest.tar